-- ============================================================
-- DreamSpace Architect — Supabase SQL Setup
-- ============================================================
-- Run this entire file once in the Supabase SQL Editor.
--
-- Authentication model:
--   Named players are identified by a UUID stored in localStorage.
--   There is no Supabase Auth — the anon key is the security
--   boundary. RLS policies are permissive (no auth.uid() checks).
--   Anonymous players never write to the database.
--
-- Tables created:
--   1. player_profiles          — one row per registered player
--   2. player_mission_progress  — one row per player × mission
-- ============================================================


-- ============================================================
-- HELPER: auto-update updated_at on every row change
-- ============================================================

create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


-- ============================================================
-- TABLE 1: player_profiles
--
-- Stores each named player's identity and aggregate score.
-- The id is a UUID generated by the database on insert and
-- returned to the client, which stores it in localStorage.
-- ============================================================

create table if not exists player_profiles (

  -- Primary key — generated by the DB on insert.
  -- Returned to the client and stored in localStorage as the
  -- player's identity token for future sessions.
  id                uuid        primary key default gen_random_uuid(),

  -- The name shown to the player (original casing, e.g. "CoolDesigner42").
  username_display  text        not null,

  -- Lowercase + trimmed version used for uniqueness checks and
  -- cross-device login. Stored separately so lookups are always
  -- case-insensitive without a function index.
  username_normalized text      not null unique,

  -- Optional email stored for the player's reference only.
  -- Not used for authentication.
  email             text        unique,

  -- Running total of the player's latest score per mission,
  -- summed across all completed missions.
  -- Updated by the application whenever a mission is submitted.
  total_score       integer     not null default 0,

  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),

  -- Set by the application on each successful login.
  last_login_at     timestamptz

);

-- Indexes
create index if not exists idx_profiles_username_normalized
  on player_profiles (username_normalized);

create index if not exists idx_profiles_email
  on player_profiles (email);

-- Auto-update updated_at
create trigger trg_profiles_updated_at
  before update on player_profiles
  for each row execute function set_updated_at();

-- Row Level Security
alter table player_profiles enable row level security;

-- All operations permitted via the anon key.
-- Security boundary: anon key must never be exposed server-side.
create policy "profiles: open access"
  on player_profiles for all
  using (true)
  with check (true);


-- ============================================================
-- TABLE 2: player_mission_progress
--
-- Tracks each player's state for every mission they have
-- touched. One row per player × mission pair (enforced by
-- the unique constraint below).
--
-- status values:
--   not_started — row exists but player hasn't placed anything
--   in_progress — player has placed items but not submitted
--   completed   — player has submitted and received a score
-- ============================================================

create table if not exists player_mission_progress (

  id          uuid        primary key default gen_random_uuid(),

  -- Which player this row belongs to.
  player_id   uuid        not null
                          references player_profiles(id)
                          on delete cascade,

  -- Matches the mission id strings defined in src/data/missions.js
  -- e.g. 'bedroom-alex', 'reading-nook-sam'
  mission_id  text        not null,

  -- Lifecycle state of this mission for this player.
  status      text        not null default 'not_started'
                          check (status in ('not_started', 'in_progress', 'completed')),

  -- Full snapshot of placed items, stored as JSON.
  -- Null until the player places their first item.
  -- Example: [{ "itemId": "bed", "x": 2, "y": 1, "rotated": false }, ...]
  room_state  jsonb,

  -- Score from the most recent completed attempt.
  -- 0 until the mission has been submitted at least once.
  latest_score  integer   not null default 0,

  -- How many times the player has submitted this mission.
  attempts    integer     not null default 0,

  started_at    timestamptz,
  completed_at  timestamptz,
  updated_at    timestamptz not null default now()

);

-- One row per player × mission — prevents duplicates.
alter table player_mission_progress
  add constraint uq_player_mission unique (player_id, mission_id);

-- Indexes
create index if not exists idx_progress_player_id
  on player_mission_progress (player_id);

create index if not exists idx_progress_mission_id
  on player_mission_progress (mission_id);

-- Auto-update updated_at
create trigger trg_progress_updated_at
  before update on player_mission_progress
  for each row execute function set_updated_at();

-- Row Level Security
alter table player_mission_progress enable row level security;

-- All operations permitted via the anon key.
create policy "progress: open access"
  on player_mission_progress for all
  using (true)
  with check (true);
